CREATE TABLE IF NOT EXISTS reports (
  id SERIAL PRIMARY KEY,
  il INTEGER NOT NULL,
  ay TEXT NOT NULL,
  ev TEXT NOT NULL,
  kiraye NUMERIC(12, 2) NOT NULL DEFAULT 0,
  kohne_isiq NUMERIC(12, 2) NOT NULL DEFAULT 0,
  yeni_isiq NUMERIC(12, 2) NOT NULL DEFAULT 0,
  serfiyyat NUMERIC(12, 2) NOT NULL DEFAULT 0,
  isiq_pulu NUMERIC(12, 2) NOT NULL DEFAULT 0,
  su_nefer NUMERIC(12, 2) NOT NULL DEFAULT 0,
  su_cem NUMERIC(12, 2) NOT NULL DEFAULT 0,
  wifi NUMERIC(12, 2) NOT NULL DEFAULT 0,
  total NUMERIC(12, 2) NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vehicle_events (
  id SERIAL PRIMARY KEY,
  plate TEXT NOT NULL DEFAULT '',
  direction TEXT NOT NULL CHECK (direction IN ('entry', 'exit')),
  source TEXT NOT NULL DEFAULT 'manual',
  confidence NUMERIC(5, 4),
  image_url TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS wash_expenses (
  id SERIAL PRIMARY KEY,
  expense_date DATE NOT NULL,
  title TEXT NOT NULL,
  amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  note TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS wash_water_readings (
  id SERIAL PRIMARY KEY,
  il INTEGER NOT NULL,
  ay TEXT NOT NULL,
  old_reading NUMERIC(12, 2) NOT NULL DEFAULT 0,
  new_reading NUMERIC(12, 2) NOT NULL DEFAULT 0,
  price_per_unit NUMERIC(12, 2) NOT NULL DEFAULT 1,
  usage_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  total NUMERIC(12, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS glossgarage_services (
  id SERIAL PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'Xidmət',
  sedan_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
  suv_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
  notes TEXT NOT NULL DEFAULT '',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS glossgarage_jobs (
  id SERIAL PRIMARY KEY,
  customer_name TEXT NOT NULL DEFAULT '',
  plate TEXT NOT NULL,
  vehicle_type TEXT NOT NULL CHECK (vehicle_type IN ('sedan', 'suv')),
  service_date DATE NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  images JSONB NOT NULL DEFAULT '[]'::jsonb,
  total NUMERIC(12, 2) NOT NULL DEFAULT 0,
  note TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
